### ISSUE TITLE
Caching Contract/Token

### ISSUE THREAD

**Issue by leafyoung** [credmark/credmark-model-framework-py#78]
Calling web3 even for the symbol name is slow.
We could create the Token object in one model, pass it to other models. The same query to web3 may run multiple of times.
We can cache the loaded Contract/Token with respect to the inputs for initialization, chain_id and block_number.

**Comment by iwyrkore** [comment]
@newtectonics and I discussed this. When a model returns a token, most times you just want the address and don't want the meta data. When passing a token as input, it could sometimes be useful to send in more meta data if it's available. Since it's the same DTO, I think we'd need to add a method that could be used when using it as input.

Perhaps something like this:

```
self.context.models.example.foobar(token=token.withMetadata())
```

Alternatively, we could have a `token.metadata` model that returns the metadata for a token address on a given chain_id and block_number and the results would be cached.

**Comment by iwyrkore** [comment]
@leafyoung Is this still relevant?

**Comment by leafyoung** [comment]
The performance bottleneck has been reduced. Let's close this for now.
